import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";

import { Roboto } from "next/font/google";

import CardSection from "@ast/components/card-section/card-section";
import Card from "@ast/components/card/asteroid-card";
import Header from "@ast/components/header/header";
import HomeStyle from "@ast/styles/Home.module.css";
import ButtonContainer from "@ast/components/button-container/button-container";
import ContentSection from "@ast/components/content-section/content-section";
import useToggle from "@ast/hooks/toggle";
import Modal from "@ast/components/modal/modal";
import FilterCard from "@ast/components/card-filter/card-filter";
import Overlay from "@ast/components/overlay/overlay";
import DatePick from "@ast/components/date-picker/datePicker";
import { PrimaryButton } from "@ast/components/buttons/buttons";
import useKeyPress from "@ast/hooks/keyPress";
import { GetStaticProps } from "next";
import { GraphQLClient, gql } from "graphql-request";
import { NeoResult } from "@ast/request/type/asteroids";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "500"] });

export const getStaticProps: GetStaticProps = async () => {
  const endPoint = process.env.END_POINT as string;

  const graphlQLClient = new GraphQLClient(endPoint);

  const query = gql`
    {
      asteroids {
        id
        name
        name_limited
        absolute_magnitude_h
        designation
        is_potentially_hazardous_asteroid
      }
    }
  `;

  const data = await graphlQLClient.request(query);

  return {
    props: { data },
  };
};

export default function Home({data}: {data: NeoResult}) {
  const [showFilters, setShowFilters] = useToggle();
  const ref = useRef<HTMLDivElement | null>(null);

  useKeyPress("Escape", () => {
    showFilters && setShowFilters();
  });

  const handleScrollToComponent = () => {
    if (ref) {
      ref.current?.scrollIntoView({ behavior: "smooth" });
    }
  };

  const GlobalStyle = (
    <style jsx global>
      {`
        body {
          overflow-y: ${showFilters ? "hidden" : "none"};
        }
      `}
    </style>
  );

  return (
    <>
      <Head>
        <title>Look up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {GlobalStyle}

      <Header
        className={roboto.className}
        mainText={
          <Header.MainText>
            Sometimes we should
            <span
              style={{
                textDecoration: "line-through",
                margin: "0 1rem 0 1rem",
              }}
            >
              LOOK UP and
            </span>
            see the beautifulness of space
          </Header.MainText>
        }
      />

      <main className={`${roboto.className} ${HomeStyle.main}`}>
        {showFilters && (
          <Modal>
            {
              <FilterCard className={`${roboto.className}`}>
                <FilterCard.Title>Filter By:</FilterCard.Title>
                <FilterCard.DateContainer>
                  <FilterCard.SubText>FROM</FilterCard.SubText>
                  <DatePick className={`${HomeStyle.dates}`} />
                  <FilterCard.SubText>TO</FilterCard.SubText>

                  <DatePick className={`${HomeStyle.dates}`} />
                </FilterCard.DateContainer>
              </FilterCard>
            }
          </Modal>
        )}
        <div ref={ref}></div>
        {showFilters && (
          <Overlay onClick={() => setShowFilters()} toggleState={showFilters} />
        )}

        <ContentSection>
          <ButtonContainer>
            <PrimaryButton
              value="Filter"
              width="90%"
              onClick={() => {
                setShowFilters();
                handleScrollToComponent();
              }}
            />
          </ButtonContainer>

          <CardSection>
            {data.asteroids?.map((neo) => (
              <Card
                key={neo.id}
                check={false}
                image={
                  <Card.ImageContainer>
                    <Image
                      src="/images/ex1.jpeg"
                      alt={neo.name_limited}
                      fill
                      style={{ objectFit: "cover", borderRadius: "1rem" }}
                    />
                  </Card.ImageContainer>
                }
                info={
                  <Card.Info>
                    <Card.InfoTitle>{neo.name}</Card.InfoTitle>

                    <Card.InfoEventContainer>
                      <Card.InfoLocation>
                        {neo.is_potentially_hazardous_asteroid}
                      </Card.InfoLocation>
                      <Card.InfoLocation>{neo.designation}</Card.InfoLocation>
                    </Card.InfoEventContainer>
                  </Card.Info>
                }
              />
            ))}
          </CardSection>
        </ContentSection>
      </main>
    </>
  );
}
